name: CI
on:
  push:
  pull_request:
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  TZ: UTC
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: actions/checkout
      uses: actions/checkout@v4
    - name: docker/metadata-action
      id: docker_metadata
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
      env:
        DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
    - name: docker/setup-qemu-action
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: docker/setup-buildx-action
      uses: docker/setup-buildx-action@v3
    - name: docker/login-action
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: docker/build-push-action
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/arm64
        push: true
        sbom: true
        provenance: mode=max
        tags: |
          ${{ steps.docker_metadata.outputs.tags }}
        labels: |
          ${{ steps.docker_metadata.outputs.labels }}
          git.sha=${{ github.sha }}
        annotations: |
          ${{ steps.docker_metadata.outputs.annotations }}
          manifest,index:git.sha=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
